### ISSUE TITLE
Snapshot tests fail on changed CSS class names inside Github action

### ISSUE THREAD

**Issue by TeemuKoivisto** [testing-library/svelte-testing-library#200] opened 2022-07-14 12:22 UTC
Hey,

so not sure what exactly is the main cause of this. But I figured since I am using testing-library's `render` method this could be the first place to ask.

So I have this project https://github.com/TeemuKoivisto/prosemirror-dev-toolkit where I just recently readded unit tests using Vitest. It's mostly been a nice breathe of fresh air coming from Jest. Yet there's one problem still remaining.

I have a [Github action pipeline](https://github.com/TeemuKoivisto/prosemirror-dev-toolkit/blob/master/.github/workflows/pull-request.yml) where I run unit tests using `yarn test:unit`. [These, at the moment, fail](https://github.com/TeemuKoivisto/prosemirror-dev-toolkit/runs/7339525559?check_suite_focus=true) due to class names being different in the snapshot [in this test](https://github.com/TeemuKoivisto/prosemirror-dev-toolkit/blob/fix-trs-empty-array-unit-tests/core/src/components/__tests__/DevTools.spec.ts#L24):

```
                    <ul
-                   class="tree-view svelte-tree-view s-kiBEL6mEiIqN"
+                   class="tree-view svelte-tree-view s-nJtgFkeMYUo5"
                    >
```

and so on. Locally of course the tests run fine. Is this a bug or have I missed something?

**Comment by yanick** [comment] 2022-07-14 13:46
This is not a bug. The per-component class names are not guaranteed to be the same across different machines. Off the top of my head, there are two things you can try:

1. In your svelte configuration for tests, change the `csshash` parameter t(https://svelte.dev/docs#compile-time-svelte-compile) o be a function that returns the empty string.
2. write a vitest custom serializer (https://vitest.dev/guide/snapshot.html#custom-serializer) that strips off the custom css classes.

**Comment by TeemuKoivisto** [comment] 2022-07-15 09:50
Okay thanks. May not be a bug but pretty frustrating thing to configure by yourself I might say.

I didn't want to write my own custom serializer so I tried passing my own `cssHash` option. Interestingly, passing it directly to `@sveltejs/vite-plugin-svelte` compilerOptions:

```js
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

export default defineConfig({
  plugins: [svelte({
    compilerOptions: {
      cssHash: ({ hash, css, name, filename }) => {
        return `s-${name}-${hash(css)}`;
      }
    }
  })],
  test: ...
})
```

didn't work. Only using `experimental` options I managed to bypass the default CSS class name generation:
```js
  plugins: [svelte({
    experimental: {
      dynamicCompileOptions: () => {
        return {
          cssHash: ({ hash, css, name, filename }) => {
            return `s-${name}-${hash(css)}`;
          }
        }
      }
    }
  })],
  test: ...
```

So I'm wondering will this solution suffice for the long run or will it break down the road?

**Comment by yanick** [comment] 2024-01-24 22:32
> So I'm wondering will this solution suffice for the long run or will it break down the road?

It might have to be tweaked if svelte takes the configuration out of experimental. But since this is a svelte behavior, and doesn't involve svelte-testing-library proper, I'll close the issue.

**Closed by yanick** 2024-01-24 22:32 UTC

**Comment by yairkukielka** [comment] 2024-05-19 11:33
You might be interested in this vitest css hash option, specially if you're using snapshots: 
https://vitest.dev/config/#css-modules-classnamestrategy
Use 'stable'
