### ISSUE TITLE
`disabled` property is not set

### ISSUE THREAD

**Issue by pontakornth** [testing-library/svelte-testing-library#191] opened 2022-05-31 08:06 UTC
For some reason, `disabled` prop does not seem to set in testing. It is missing.

## How to re-produce
1. Setup a component (named DisabledButton.svelte)
    ```svelte
    <button disabled>Disabled</button>
   ```
2. Write this test
   ```javascript
   import DisableButton from './DisableButton.svelte';
   import '@testing-library/jest-dom';
   import { render, screen } from '@testing-library/svelte';
   describe('DisableButton', () => {
	   it('is disabled', () => {
		   render(DisableButton);
		   screen.debug();
		   expect(screen.getByRole('button').hasAttribute('disabled')).toBeTruthy();
	   });
   });
   ```

## Expected behavior
The test passes.

## Actual behavior
It fails and `debug` function prints button without `disabled` prop.

I think it maybe either a bug or something is wrong in my setup.

**Comment by mcous** [comment] 2024-01-24 08:20
@pontakornth are you still having this issue? I am unable to reproduce it; your test above passes in a minimal Jest + svelte-testing-library setup. I think you're right, there is/was probably something wrong with your setup. I also recommend you use `expect(...).toBeDisabled()` over that `hasAttribute() + toBeTruthy()` combination.

@yanick I can't find any problems here, so I think we can close this issue

**Comment by pontakornth** [comment] 2024-01-24 09:11
@mcous I don't have access to the code anymore. I think if you cannot reproduce the issue, it should be fine now. This issue is already more than a year old also. Also, thank you for `toBeDisabled` guide.

**Comment by yanick** [comment] 2024-01-24 16:59
Woo. The backlog is melting! \o/

**Closed by yanick** 2024-01-24 16:59 UTC
